### ISSUE TITLE
Linking to the source-code

### ISSUE THREAD

**Issue by frankhaugen** [dotnet/apisof.net#14]
I find this to be an awesome tool but I wish I could use it to lookup the source-code, (a link to the file the class/method lives in).

Having looked at the possibilities this is probably possible with enough people, but it looks very convoluted to do, making it almost simpler to decompile the dlls and extracting and displaying the code-files.

But I would still like it, as it would help looking into dotnet source-code for reference

**Comment by terrajobst** [comment]
Hmm, I don't think decompilation would be the most useful result. I'm thinking a combination of:

1. Using debugging symbols to find the corresponding location on github.com
2. Linking to source.dot.net

(1) will work well for NuGet packages but doesn't work well for the platform itself as I'm not indexing the implementation, I index what we call "reference pack", which is essentially the managed equivalent of header files. Those don't contain any code, so there is no source information that I could index.

(2) is a feature @KirillOsenkov and I have been talking about for years. That would work well for the platform layer but not necessarily many of our packages.

**Comment by frankhaugen** [comment]
@terrajobst cool! I just did a quick skim of his repo on my phone, but if there was API -endpoints that could be queried in some sensible manner, someone could get code down to the member -level details.

Just linking seems too easy, and it's much cooler to host the code in your UI

**Comment by terrajobst** [comment]
We're now linking to source.dot.net and sourceroslyn.io

**Comment by WeihanLi** [comment]
@terrajobst  thanks very much for the feature, is it possible to link to the github source code also? and how often is the sync between github source code and source.dot.net?
