### ISSUE TITLE
Distinguish current framework & legend.

### ISSUE THREAD

**Issue by JonDouglas** [dotnet/apisof.net#36]
When searching for APIs, I noticed there's a blue "current" framework pill. The problem is for me that I cannot easily tell if it is built-in, package-provided, etc because it's a unique selected color compared to others. Usually have to click off of it to see the respective color.

Suggestion: Use an underline or a way to contrast the current color instead of blue to not confuse the legend below.

<img width="1916" alt="image" src="https://user-images.githubusercontent.com/1288848/198673780-349e79e8-fd8f-4e3e-816c-384f83b8d9ba.png">

**Comment by terrajobst** [comment]
That's a good point. So far, I was too lazy to do that :-)

**Comment by terrajobst** [comment]
Fixed as of now
