### ISSUE TITLE
Missing Package: Microsoft.Cci.Extensions

### ISSUE THREAD

**Issue by reecebradley** [dotnet/apisof.net#42]
I was trying follow the [programmatic](https://github.com/dotnet/apisof.net/blob/main/docs/upgrade-planner/programmatic-access.md) approach to this library. However, upon installing `Terrajobst.NetUpgradePlanner`, one of its dependencies went missing

```sh
dotnet add package Terrajobst.NetUpgradePlanner --version 0.1.9-beta
```

I get the error:
`error: NU1101: Unable to find package Microsoft.Cci.Extensions. No packages exist with this id in source(s)`

So I went to the NuGet: https://www.nuget.org/packages/Terrajobst.NetUpgradePlanner#dependencies-body-tab
![image](https://user-images.githubusercontent.com/1536861/234305373-d132a1ea-864d-4c64-af60-f9126a9fdec5.png)

I get the "Oops! 404 not found..." when trying to see [Microsoft.Cci.Extensions](https://www.nuget.org/packages/Microsoft.Cci.Extensions/)

FYI: My organization really wants to generate reporting of this information for now and future going efforts to inform leadership possible effort that could be imposed on dev teams.

**Comment by terrajobst** [comment]
Fixed by #43
