### ISSUE TITLE
System.IO.FileInfo.GetAccessControl not available on .Net core

### ISSUE THREAD

**Issue by lbcsy** [dotnet/apisof.net#46]
### Version

0.1.43-beta (e38ec9599f5aecd2a719085906ca6348b4b2d977)

I am checking a .NET 4.8 library with .NET Upgrade Planner, and set the desired framework and platform to .NET Standard 2.0 and Windows. There is only one place in my code is using System.IO.File.GetAccessControl, I then changed the code to use System.IO.FileInfo.GetAccessControl which is also available in .NET Standard 2.0, but .NET Upgrade Panner shows System.IO.FileInfo.GetAccessControl as an upgrade problem, why?

**Comment by terrajobst** [comment]
[System.IO.FileInfo.GetAccessControl()](https://apisof.net/catalog/724629c3-c9da-1098-bec4-02601a8a82f7) doesn't actually exist in .NET Standard.

[https://apisof.net/catalog/15e6eebc-ff97-5540-4248-5c691358341f](https://apisof.net/catalog/15e6eebc-ff97-5540-4248-5c691358341f) does, which isn't binary compatible.

But you're raising a good point, .NET Upgrade Planner should do a better job handling those.

**Comment by terrajobst** [comment]
I'm closing as by-design.
