### ISSUE TITLE
Add a way to filter API diffs

### ISSUE THREAD

**Issue by MichalPetryka** [dotnet/apisof.net#58]
It'd be nice to be able to filter diffs to for example only show APIs present on the left side, ignore attribute changes and such.

Here's a simple filter list from an example diff tool for inspiration of what could be useful:
![image](https://github.com/dotnet/apisof.net/assets/35800402/6b361527-d2ba-46cb-a6b4-960158a2a2be)

**Comment by terrajobst** [comment]
Is that that "unique items" means?

"Show left unique items" -> "Show Removed"
"Show right unique items" -> "Show Add"

**Comment by terrajobst** [comment]
<img width="400" alt="image" src="https://github.com/dotnet/apisof.net/assets/5169960/d8666209-7fb8-4e1e-a0b6-1302a22ddba9">
