### ISSUE TITLE
The docs link seemed removed

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/apisof.net#60]
![image](https://github.com/dotnet/apisof.net/assets/7604648/2f776719-bc07-4cf1-8591-2493c4a347ea)

It seemed the docs/learn link had been removed, it would be great if we could add it back

In the docs page, there's more helpful info

fo example, we could get the Derived types info and link to the github source and maybe some useful examples

![image](https://github.com/dotnet/apisof.net/assets/7604648/3cba3017-b14f-4a09-8e89-07753c39906c)

**Comment by terrajobst** [comment]
Should be fixed with d1bdbdfbab68a0b1fb5c7a63bd2d6416b503e30f.
