### ISSUE TITLE
The source url not working

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/apisof.net#67]
For example: 
From the `ReadOnlySpan` api page, https://apisof.net/catalog/6a4fbf2b1f8641524ea0fa2dfb047442

The source linked to:
https://source.dot.net/System.Private.CoreLib/A.html#2bbf4f6a861f5241

When open it, it redirects to a bad page

![image](https://github.com/user-attachments/assets/9f1a24db-b5c1-4524-8bcd-a7aa60c96d85)

While when searching in https://source.dot.net directly, it looks good, maybe an issue for `source.dot.net`?

![image](https://github.com/user-attachments/assets/0cfff8d6-b7db-4a8b-b0d5-b10f724d8671)

The issue also exists for other APIs

**Comment by terrajobst** [comment]
I can't repro this issue:

- Tried with Edge
- Tried with Chrome
- Tried with Firefox

Maybe it was a temporary issue with source.dot.net?

**Comment by WeihanLi** [comment]
Maybe something with my network or browser, works on another device, sorry for the time

**Comment by terrajobst** [comment]
No worries at all :-)
